version: '3.4'

networks:
  net:

services:
  auth-app:
    image: ${DOCKER_REGISTRY-}auth-app
    build:
      context: .
      dockerfile: Authorization/WebApp/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: mssql
    container_name: mssql
    environment:
      -  ACCEPT_EULA=Y
      -  SA_PASSWORD=Password12!
    ports:
      - "1433:1433"
    networks:
      - net

  weatherservice:
    image: ${DOCKER_REGISTRY}weatherservice
    build:
      context: .
      dockerfile: TestSystem/ProtectedResources/WeatherService/Api/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY}webapp
    build:
      context: .
      dockerfile: TestSystem/Web/Dockerfile

  spa:
    image: ${DOCKER_REGISTRY-}spa
    build:
      context: .
      dockerfile: TestSystem/SinglePage/Server/Dockerfile

