version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: mssql
    container_name: mssql
    environment:
      -  ACCEPT_EULA=Y
      -  SA_PASSWORD=Password12!
    ports:
      - "1433:1433"
