version: '3.4'

networks:
  net:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Authorization/Api/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: mssql
    container_name: mssql
    environment:
      -  ACCEPT_EULA=Y
      -  SA_PASSWORD=Password12!
    ports:
      - "1433:1433"
    networks:
      - net