FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Authorization/Application", "Application/"]
COPY ["Authorization/Domain", "Domain/"]
COPY ["Authorization/Infrastructure", "Infrastructure/"]
COPY ["Authorization/WebApp", "WebApp/"]
RUN dotnet restore "WebApp/WebApp.csproj"
WORKDIR "/src/WebApp"
RUN dotnet build "WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApp.dll"]