version: '3.9'

services:
  authorizationserver:
    image: jokk/authorizationserver
    ports:
      - 5000:80
    container_name: 'authorizationserver'
    volumes:
      - ./Identity.db:/app/Identity.db:ro
    environment:
      - CONNECTIONSTRINGS__SQLite=Data Source=./Identity.db
  
  webapp:
    image: jokk/webapp
    ports:
      - 5001:80
    container_name: 'webapp'

  configurationapp:
    image: jokk/configurationapp
    container_name: 'configurationapp'
    environment:
      - CONNECTIONSTRINGS__SQLite=Data Source=./Identity.db
    volumes:
      - ./Identity.db:/app/Identity.db:rw
  
  nginx:
    image: 'nginx/nginx'
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot