version: '3.9'

services:
  authorizationserver:
    image: jokk/authorizationserver
    restart: on-failure
    container_name: 'authorizationserver'
    ports:
      - 5000:80
    volumes:
      - ./Identity.db:/app/Identity.db:rw
    environment:
      - CONNECTIONSTRINGS__SQLite=Data Source=./Identity.db
      - Identity__Issuer=https://idp.authserver.dk
      - ASPNETCORE_ENVIRONMENT=Production
  
  webapp:
    image: jokk/webapp
    restart: on-failure
    container_name: 'webapp'
    ports:
      - 5001:80
    depends_on:
      - authorizationserver
    environment:
      - Identity__Authority=https://idp.authserver.dk
      - Identity__ClientUri=https://app.authserver.dk
      - WeatherService__Url=https://weather.authserver.dk
      - ASPNETCORE_ENVIRONMENT=Production

  weatherservice:
    image: jokk/weatherservice
    restart: on-failure
    container_name: weatherservice
    depends_on: authorizationserver
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Identity__Authority=https://idp.authserver.dk    

  configurationapp:
    image: jokk/configurationapp
    container_name: 'configurationapp'
    environment:
      - CONNECTIONSTRINGS__SQLite=Data Source=./Identity.db
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./Identity.db:/app/Identity.db:rw
  
  nginx:
    image: 'nginx'
    restart: on-failure
    container_name: 'nginx'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - authorizationserver
      - webapp

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot