name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
  
env:
  DOTNET_NOLOGO: true

jobs:
  build_solution:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: 'Password12!'
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Install tools
      run: |
        dotnet tool install --global JetBrains.dotCover.GlobalTool
        dotnet tool install --global dotnet-sonarscanner
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'
    - name: Restore dependencies
      run: dotnet restore authserver.sln
    - name: Analyze
      run: |
        dotnet-sonarscanner begin /k:"jokk-itu_authserver" /o:"jokk-itu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.scanner.skipJreProvisioning=true
        dotnet build authserver.sln --no-restore
        dotnet dotcover test --dcReportType=HTML
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  
  build_documentation:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          cd doc
          npm install
          npm run build