name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:

  push_to_container_registry:
    name: Push Images to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Sign in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images
        run: |
          docker build . -f Authorization/WebApp/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/authorizationserver:latest
          docker build . -f Authorization/ConfigurationApp/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/configurationapp:latest
          docker build . -f Clients/WebApp/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/webapp:latest
      
      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/authorizationserver:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/configurationapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/webapp:latest
  
  deploy_containers:
    name: Deploy Containers on Test environment
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3

  deploy_documentation_app:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          cd Documentation
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Documentation/build
